### ISSUE TITLE
Domanda sul portale

### ISSUE THREAD

**Issue by fulcorno** [TdP-prove-finali/OliveroFederico#2]
Ho notato che non hai ancora inserito sul portale la domanda per lo svolgimento della Prova Finale che avevo approvato.
Per favore procedi (a meno che non abbia cambiato idea), così potrai poi fare domanda di conclusione finale.

**Comment by federico2879** [comment]
Salve prof, 
mi scusi ma non capisco cosa intende; io avevo fatto la richiesta conferma conclusione per potermi iscrivere all'esame finale di laurea, che lei mi aveva approvato il 13 novembre, e mi sono laureato il 24; inoltre ho caricato l'elaborato sul disco condiviso.
Cosa intende con inserito sul portale la domanda per lo svolgimento?

**Comment by fulcorno** [comment]
Evidentemente ho sbagliato io ad aggiornare qualche elenco.
Correggo subito, scusa per il disturbo
Fulvio

**Comment by federico2879** [comment]
ok perfetto, si figuri nessun problema
